name: Build Godot Project With Latest Codes

on:
  push: {}
  pull_request: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Godot:
    name: "构建游戏"
    env:
      dev_ver:
        "1.0.0"
      dev_text:
        "dev build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        name: "运行 actions/checkout@v4.2.1"
        with:
          lfs: true
      - name: 获取标签或commit id
        id: get-version-id
        uses: iawia002/get-tag-or-commit-id@v1.0.1
        with:
          length: 7
      - name: 安装 wine
        id: wine_install
        run: |
          sudo apt install wine64
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: 获取测试名
        id: test_name
        run: |
          export name=$(cat test_name.txt)
          echo $name
          echo "name=$(cat test_name.txt)" >> "$GITHUB_OUTPUT"
      - name: 检测 commit id 是否正常并设置安卓导出相关设置
        run: |
          echo "COMMIT ID:" ${{steps.get-version-id.outputs.id}}
          export GODOT_ANDROID_KEYSTORE_DEBUG_PATH=.\debug.keystore
          export GODOT_ANDROID_KEYSTORE_DEBUG_USER=root
          export GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD=123456
          export GODOT_ANDROID_KEYSTORE_RELEASE_PATH=.\release.keystore
          export GODOT_ANDROID_KEYSTORE_RELEASE_USER=root
          export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=123456
      - name: 设置 JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 设置 Android SDK
        uses: android-actions/setup-android@v3.2.1
      - name: 设置项目名称
        run: |
          sed -i "s/Baldi godot remake/Baldi's Basics In Education And Learning - ${{env.dev_text}}/g" project.godot
          sed -i "s/0.0.0.0/${{env.dev_ver}}/g" project.godot
          sed -i "s/Dev Build/commit id: ${{steps.get-version-id.outputs.id}} - ${{steps.test_name.outputs.name}}/g" scenes/player.tscn
      - name: 导出游戏
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-dev5/Godot_v4.4-dev5_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-dev5/Godot_v4.4-dev5_export_templates.tpz
          relative_project_path: ./
          export_debug: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
          cache: true
      - name: 设置 Github Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: 上传 Github Pages 构建
        uses: actions/upload-pages-artifact@v3
        with:
          path: '/home/runner/.local/share/godot/builds/Web'
      - name: 部署 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: 为 Linux x64 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Linux x64 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Linux x64/linux.x86_64
      - name: 为 Linux x86 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Linux x86 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Linux x86/linux.x86_32
      - name: 为 Linux arm64 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Linux arm64 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Linux arm64/linux.arm64
      - name: 为 Linux arm32 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Linux arm32 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Linux arm32/linux.arm32
      #- name: 为 Linux rv64 上传构建
      #  uses: actions/upload-artifact@v4.4.3
      #  with:
      #    name: Linux rv64 - 构建 ${{steps.get-version-id.outputs.id}}
      #    path: /home/runner/.local/share/godot/builds/Linux rv64/linux.rv64
      #- name: 为 Linux rppc64 上传构建
      #  uses: actions/upload-artifact@v4.4.3
      #  with:
      #    name: Linux ppc64 - 构建 ${{steps.get-version-id.outputs.id}}
      #    path: /home/runner/.local/share/godot/builds/Linux ppc64/linux.ppc64
      #- name: 为 Linux ppc32 上传构建
      #  uses: actions/upload-artifact@v4.4.3
      #  with:
      #    name: Linux ppc32 - 构建 ${{steps.get-version-id.outputs.id}}
      #    path: /home/runner/.local/share/godot/builds/Linux ppc32/linux.ppc32
      #- name: 为 MacOS 上传构建
      #  uses: actions/upload-artifact@v4.4.3
      #  with:
      #    name: MacOS - 构建 ${{steps.get-version-id.outputs.id}}
      #    path: /home/runner/.local/share/godot/builds/macOS/mac.zip
      - name: 为 Windows x64 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Windows x64 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Windows Desktop x64/win64.exe
      - name: 为 Windows x86 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Windows x86 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Windows Desktop x86/win86.exe
      - name: 为 Windows arm64 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Windows arm64 - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Windows Desktop arm64/winarm64.exe
      - name: 为 Android 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Android - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Android/android.apk
      - name: 打包 Web 构建
        run: |
          cp ./start.exe /home/runner/.local/share/godot/builds/Web
          7z a /home/runner/.local/share/godot/builds/Web/web.zip /home/runner/.local/share/godot/builds/Web/*
      - name: 为 Web 上传构建
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Web - 构建 ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Web/web.zip
